// Auto-generated by technical_agent.py — regenerate rather than hand-edit.
// Deliberately plain JavaScript (no TS types) so this works whether the
// project is JS or TS — Next.js only needs the file extension to be .js/.ts,
// it doesn't require type annotations inside it.
export default function sitemap() {
  return [
  { url: "https://holovox-jade.vercel.app/", lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
  { url: "https://holovox-jade.vercel.app/", lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 }
  ];
}
